### PR TITLE
Update tf version to 0.15.1 and update providers

### PR DESCRIPTION
**Pull request by theinrichs**

### CODE REVIEW

**Review by maxbischoff — APPROVED** [review]
Thanks 👍

**Comment by maxbischoff** [comment]
Seems like the versions need to be bumped in https://github.com/inovex/lfs458-course-prep/blob/master/.github/workflows/terraform.yml

**Review by maxbischoff — CHANGES_REQUESTED** [review]
Please bump the terraform versions in [.github/workflows/terraform.yml](https://github.com/inovex/lfs458-course-prep/blob/master/.github/workflows/terraform.yml)

**Comment by maxbischoff** [comment]
Needs a rebase, then the terraform actions should work again

**Comment by theinrichs** [comment]
I close this, all the merges from before are breaking the rebase beyond repair...

**Pull request closed without merging**
